#!/usr/bin/env bash
# a comment
func () {

        if [ "$2" ]
        then
                dig "${2}.${1}" +noall +answer | awk -v a="$2" '{print " The subdomain " a " is a " $4 " record and points to " $5}'
        else
                dig "www.${1}" +noall +answer | awk '{print " The subdomain www is a " $4 " record and points to " $5}'
                dig "lb-01.${1}" +noall +answer | awk '{print " The subdomain lb-01 is a " $4 " record and points to " $5}'
                dig "web-01.${1}" +noall +answer | awk '{print " The subdomain web-01 is a " $4 " record and points to " $5}'
                dig "web-02.${1}" +noall +answer | awk '{print " The subdomain web-02 is a " $4 " record and points to " $5}'
        fi
}
if [ "$2" ]
then
        func "$1" "$2"
else
        func "$1"
fi
