#!/usr/bin/env bash
# a comment
apt-get -y update
apt-get -y install nginx

chmod 666 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx restart
