#!/usr/bin/env bash
# a comment
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
echo "http {
        include mime.types;

        server {
                listen 80;
                root /var/www/html;
                location / {
                        root /var/www/html;
                }
                location redirect_me {
                    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
                }
        }
}
events {}" > /etc/nginx/nginx.conf
sudo service nginx restart
