#!/usr/bin/env bash
# a comment
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "http {
        include mime.types;

        server {
                listen 80;
                root /var/www/html/;
                index index.nginx-debian.html;
                location /redirect_me/ {
                    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
                }
        }
}
events {}" > /etc/nginx/nginx.conf
sudo service nginx restart
