#!/usr/bin/env bash
# a comment 
#i=$(cat ./file)
sed -i 's/http {/http { server { listen 80; server_name 35.168.7.56; local \/redirect_me\/ { return 301 http:\/\/35.168.7.56\/;}}/' file
cat file
#echo "$i"
