#!/usr/bin/env bash
# prints "To infinity and beyond" indinfinetly with sleep 2 between each iteration and prints "I am invincible!!!" when SIGTERM signal is recieved
for (( ; ; ))
do
echo "To infinity and beyond"
trap "echo \"I am invincible!!!\"" SIGTERM
sleep 2
done
