#!/usr/bin/env bash
# This script prints from 1 to 100 if number multiplies by 3 and 5 prints "FizzBuzz", if number multiplies by 5 prints "Buzz" if number multiplies by 3 prints "Fizz"
for ((i=1; i<=100; i=i+1))
do
if (( i % 3 == 0 & i % 5 == 0))
then
echo "FizzBuzz"
elif (( i % 5 == 0 ))
then
echo "Buzz"
elif (( i % 3 == 0 ))
then
echo "Fizz"
else
echo "$i"
fi
done
