#!/usr/bin/env bash
# This script prints from 1 to 20 and prints "bad luck from china" after the 4th time and prints "bad luck from japan" after 9th time and prints "bad luck from italy" after the 17th time
i=1
while [ $i -le 20 ]
do
echo "$i"
case $i in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
i=$((i+1))
done
