#!/usr/bin/env bash
# change ip of localhost to 127.0.0.2 and ip of facebook.com to 8.8.8.8
echo "8.8.8.8	facebook.com" > ~/hosts.new
cat /etc/hosts >> ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
