#!/usr/bin/env bash
# a comment
#chmod 777 /etc/nginx/nginx.conf
#pkill apache2
#echo "http {
#    include mime.types;
#
 #   server {
  #      listen 80;
   #     root /var/www/html/;
    #    index index.nginx-debian.html;
#
 ##       location /redirect_me/ {
   #         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    #    }
#
 #       error_page 404 /new_err.html;
#
 #       location = /new_err.html {
  #          internal;
   #     }
   # }
#}
#events {}" > /etc/nginx/nginx.conf
#sudo -u nginx service nginx restart
#!/usr/bin/env bash
# Script for restart nginx running as user nginx on 8080
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
